# Generated by Django 2.2.5 on 2021-08-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getaway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_title',
            field=models.CharField(max_length=100),
        ),
    ]
